version: '3'
services:
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app  # Map the host working directory to the container
      - /app/node_modules  # Prevent overwriting node_modules in container
    environment:
      NODE_ENV: development
    command: npm run dev  # Use nodemon for hot reloading
